### ISSUE TITLE
Measuring behavior for total energy

### ISSUE THREAD

**Issue by x-erik** [magtimmermans/smartgateways#1]
Homey adds all devices with energy measurements to a total in the Energy tab. This Smartgateway app measures the total energy used in the building, however as this is a device it will also add up the other measurements from other devices, resulting in a total on the Energy tab which is higher than the actual usage.

Should the setting `"cumulative": true` in the driver.compose.json be added?
Or is this intentional? 

More info on the setting can be found here: [https://apps.developer.homey.app/the-basics/devices/energy#measuring-devices](https://apps.developer.homey.app/the-basics/devices/energy#measuring-devices)

**Comment by magtimmermans** [comment]
Always difficult. Some people would like to know only the energy of the device and use other ways to calculate the total energy.  I have no problems changing this now so I will update this.
