### ISSUE TITLE
In homey the app shows errors

### ISSUE THREAD

**Issue by jeroen1973** [magtimmermans/smartgateways#10]
In the homey 2019 pro there are a lot of errors in the logs, see printscreen
![Uploading IMG_4213.png…]()

**Comment by magtimmermans** [comment]
I cannot open the picture.

**Comment by jeroen1973** [comment]
Jeroen van der WalOp 14 mei 2023 om 21:39 heeft magtimmermans ***@***.***> het volgende geschreven:﻿
I cannot open the picture.

**Comment by jeroen1973** [comment]
![IMG_4213](https://github.com/magtimmermans/smartgateways/assets/29982887/29c5b41d-85c7-4b3c-94df-1676ac298bdc)

**Comment by magtimmermans** [comment]
I think you need to download the latest test version from the app store and remove the device and re-add this (will lose your history)

**Comment by jeroen1973** [comment]
I had the latest app version but removed and reinstalled, looks like all is ok now! Thanks Jeroen van der WalOp 17 mei 2023 om 10:04 heeft magtimmermans ***@***.***> het volgende geschreven:﻿
I think you need to download the latest test version from the app store and remove the device and re-add this (will lose your history)

**Comment by magtimmermans** [comment]
OK, great
