### ISSUE TITLE
Feature request/issue: S0 Gateway does not show values on Homey energy tab

### ISSUE THREAD

**Issue by mouali92** [magtimmermans/smartgateways#11]
Hii,

The S0 gateway does not show up on the energy tab. I expected that I could use the S0 Gateway to add the solar panel production on the Homey Energy Tab. Is it possible to add a property/feature so that Homey sees the S0 Gateway as solar panels?

Cheers,
Mo

**Comment by magtimmermans** [comment]
Please try the new test version on https://homey.app/a/com.cyclone-software.smartgateways/test/
if this is okay I remove the other capability.
