### ISSUE TITLE
Watermeter reset daytotal at 1 o'clock

### ISSUE THREAD

**Issue by RSlegers** [magtimmermans/smartgateways#3]
The watermeter is resetting it's day-total at 1 o'clock instead of midnight.

The Homey timezone is set to Europe/Amsterdam.

Version Homey Pro Early 2019; 7.4.1
Version Smart Gateways; 2.1.3

**Comment by magtimmermans** [comment]
That's weird. I tested this he and it is almost exact on 00:00:00 houra

**Comment by RSlegers** [comment]
That is definilty strange, what is your timezone of Homey ?

I have set Homey to send me every day at 23:59 AND 00:59 a message with the daily waterusage and they are both the same (or 00:59 is higher if there was waterusage in that hour (dishwasser, washingmachine).

I have included a Homey insight of the watermeter, and saw it resets even later than 1:00.
![watermeter](https://user-images.githubusercontent.com/6598450/172212844-5bd2056b-a869-4860-968e-a3e4772b429c.jpg)
.
And another one
![watermeter 2](https://user-images.githubusercontent.com/6598450/172213362-3b47cafd-2dbe-4535-9120-e93880ff28eb.jpg)
:

**Comment by magtimmermans** [comment]
Mmh, that's wierd indeed. I gave the same timezone. What is your homey version?

**Comment by RSlegers** [comment]
still 7.4.1 (as in the first post)

**Comment by magtimmermans** [comment]
Sorry, missed that. I will try to upgrade as I am using an older version. Maybe then I can reproduce it.

**Comment by RSlegers** [comment]
What is the status now ?
I can create a diagnostic report for you, if you like.

**Comment by magtimmermans** [comment]
Didnt find the time yet to debug.

**Comment by magtimmermans** [comment]
https://homey.app/a/com.cyclone-software.smartgateways/test/
New Test version. It seems that the date object was changed in the latest version

**Comment by RSlegers** [comment]
I have installed the test-version now for 2 days, but no change, reset is still at 2 o'clock

**Comment by magtimmermans** [comment]
So, even 1 hour later?

**Comment by RSlegers** [comment]
No, i thought it was 1 o'clock, but as you can see in the earlier posted graphs it is 2 o'clock al along.

So with the updatecthere is no change

**Comment by RSlegers** [comment]
If you want i can make a report for you from the app.

**Comment by magtimmermans** [comment]
Yes please, maybe that will help. The issues has to do with timezone (local) and Calc to midnight.

**Comment by RSlegers** [comment]
This is the repoet code : c447d51c-ad20-4916-8f0c-d1e3d3abbd14

**Comment by magtimmermans** [comment]
Found it

**Comment by RSlegers** [comment]
My report. The bug, or both ?

**Comment by magtimmermans** [comment]
Both actually. Unfortunately the report does not give me enough information. I will try to log more and make an update for the test version.

**Comment by magtimmermans** [comment]
I think I made a calculation error so the routine was not updated. 
Please try the new test version: https://homey.app/a/com.cyclone-software.smartgateways/test/

**Comment by RSlegers** [comment]
Seems solved now, will watch fot a few days, but think it is ok  now

**Comment by magtimmermans** [comment]
Ok, Let me know.

**Comment by RSlegers** [comment]
Watermeter is ok now, this can be closed.
