### ISSUE TITLE
kWh-meter giving wrong dimension in total ?

### ISSUE THREAD

**Issue by RSlegers** [magtimmermans/smartgateways#4]
the kWh-meter says on the moment i have -3.6 W total power,
My solarpanals total is 3972.13 W power, 
My current use is about 350 W power,

So i think the total power of the kWh-meter should be -3.6 kW or -3600 W

This is the case for "huidig verbruik' (i think, as it is 0 now) 'verbruik saldi' en 'huidige opbrengst'.

'verbruik per uur' is correct as its dimension is kWh.

**Comment by magtimmermans** [comment]
There is a setting you can change this

**Comment by RSlegers** [comment]
Found it, but i find the discreption unclear. The label says Meter in Wh (now set to yes)

**Comment by magtimmermans** [comment]
Correct, that's something I need to change when I have some time.
