### ISSUE TITLE
Elektra-meter momentele waardes 0

### ISSUE THREAD

**Issue by RSlegers** [magtimmermans/smartgateways#5]
Sinds 8 dagen (update 2.4.0 ?) geeft de kWh-meter voor "Huidig verbruik", "Verbruik Saldi" en "Huidige opbrengst" alleen nog maar 0 weer, de ander waarden worden wel gewoon getoond en geupdate.

**Comment by RSlegers** [comment]
Still no change, can you investigate this please ?

**Comment by magtimmermans** [comment]
De laatste versie is 2.5.0. Ik denk niet dat dit voor jou verschil zal maken omdat alleen de detectie van apparaten is veranderd. Het rare is bij mij werkt het prima. Ik heb beta testers gevraagd (11 mensen) en die hebben ook geen probleem. 

Heeft de meter een vast ip adres en homey ook?

**Comment by RSlegers** [comment]
Als het goed is hebbne ze via de de router (op MAC-adres) beide een vast IP, echter denk ik niet dat dit het probleem is, omdat Verbruik per uur, Energie saldi, totaal, piek, dal, productie piek en dal het wel gewoon doen.

Het enige dat is mis sinds 3 maanden is Huidig verbruik, Verbruik Saldi en Huidige opbrengst.

De huidige firmware versie van de Connectix smart meter gateway is 2022091501, hardwareversie 1.0
Meter is DSMR 2
App versie 2.5.0 experminental
Homey Pro (Early 2019) 8.0.6
Diagnostisch Rapport : fe1906b5-5aec-46fc-bc2e-4dbc591d4067

**Comment by magtimmermans** [comment]
Can you try http://<ip-adres-meter>:82/smartmeter/api/read? 
and sent me the results. And at the same time screenshots from Homey.

Can also directly to my e-mail address (more privatly).

**Comment by RSlegers** [comment]
{"mac_address":"XX_C9_XX_C5_A5_XX","gateway_model":"connectix_smartmeter_gateway_v1.0","startup_time":"1970-01-01T02:00:36Z","firmware_running":"2022091501","firmware_available":"2022091501","firmware_update_available":"false","wifi_rssi":"-36","mqtt_configured":"false","blynk_configured":"false","Equipment_Id":"31xx3xx9xx3xx83xx02xx02xx0202xx0","GasEquipment_Id":"Unknown","ElectricityTariff":"0002","EnergyDeliveredTariff1":"24351.21","EnergyReturnedTariff1":"4489.03","EnergyDeliveredTariff2":"17776.93","EnergyReturnedTariff2":"11272.14","PowerDelivered_total":"0.00","PowerReturned_total":"0.00","PowerDelivered_l1":"0.00","PowerDelivered_l2":"0.00","PowerDelivered_l3":"0.00","PowerReturned_l1":"0.00","PowerReturned_l2":"0.00","PowerReturned_l3":"0.00","Voltage_l1":"0.00","Voltage_l2":"0.00","Voltage_l3":"0.00","Current_l1":"0.000","Current_l2":"0.000","Current_l3":"0.000","GasDelivered":"0.00","GasDeliveredHour":"0.00","PowerDeliveredHour":"1.05","PowerDeliveredNetto":"870"}

Op di 4 okt. 2022 om 11:28 schreef magtimmermans ***@***.***>:

**Comment by RSlegers** [comment]
i see there is a header "ElectricityTariff" in de api, is it possible you
could add it to the app so it is possible to use it in flows?

Op di 4 okt. 2022 om 11:28 schreef magtimmermans ***@***.***>:

**Comment by magtimmermans** [comment]
Hoi,

De app keest het goed. De api geeft voor  "Huidig verbruik", "Verbruik Saldi" en "Huidige opbrengst" nul aan. Ik zou even contact opnemen met Smartgateways. Mbt je andere vraag ik zal dit op de todo lijst zetten.

**Comment by magtimmermans** [comment]
Please try this version with the new added measures. Remove device and re-add it.
https://homey.app/a/com.cyclone-software.smartgateways/test/
