### ISSUE TITLE
cannot add gasmeter

### ISSUE THREAD

**Issue by dianaw1977** [magtimmermans/smartgateways#6]
The gasmeter was not receiving values. so we tried to remove and add the gasmeter again.
When i try to add the app cannot find the gasmeter. 
it does find it when i try to add smart meter only then the values dont get updated.

The gasmeter is online and on the ip page of itself the values are updated. (model is connectix_gasmeter_gateway_v1.0-B. Firmware 2022061801.

**Comment by magtimmermans** [comment]
Please use the test version: https://homey.app/nl-nl/app/com.cyclone-software.smartgateways/Smart-Gateways/test/

**Comment by dianaw1977** [comment]
Hi, 

tried this version and when adding the device. i get mdnsResolver is not defined. (when it is searching for the device)

**Comment by magtimmermans** [comment]
Ok Then I need to check in the weekend what is wrong with this part..

**Comment by magtimmermans** [comment]
Please try https://homey.app/a/com.cyclone-software.smartgateways/test/

**Comment by dianaw1977** [comment]
I have tried this version and the error is gone but it cant find any new devices.

**Comment by magtimmermans** [comment]
Do you have the latest firmware? And can you reach the webpage of the device?

**Comment by dianaw1977** [comment]
Hi,

yes the page is reachable and it has the current firmware.

*Update current firmware?*

 Firmware running:     2022061801

 Firmware available:   2022061801

Reapplied the firmware and that fixed the issue.

Regards,

Diana

**Comment by magtimmermans** [comment]
Hi Diana,

So it is solved?

Marcel Timmermans
Send from my iphone


Op 27 sep. 2022 om 14:46 heeft dianaw1977 ***@***.***> het volgende geschreven:

﻿

Hi,

yes the page is reachable and it has the current firmware.

*Update current firmware?*

Firmware running: 2022061801

Firmware available: 2022061801

Reapplied the firmware and that fixed the issue.

Regards,

Diana

**Comment by dianaw1977** [comment]
Hi,
yes it is solved.
Regards,
Diana

**Comment by magtimmermans** [comment]
Great!

Marcel Timmermans
Send from my iphone


Op 27 sep. 2022 om 16:06 heeft dianaw1977 ***@***.***> het volgende geschreven:

﻿

Hi,
yes it is solved.
Regards,
Diana
