### ISSUE TITLE
Slimme meter wifi gateway - Usage  in Homey App displayed in Wh - Should be W 

### ISSUE THREAD

**Issue by Dijker** [magtimmermans/smartgateways#7]
Slimme meter wifi gateway
Deze drie zijn in Homey App (v. 3.0.2 - https://homey.app/nl-nl/app/com.cyclone-software.smartgateways/Smart-Gateways/test/ ) 
volgens weergave Wh maar zouden  m.i. W moeten zijn.  

![image](https://user-images.githubusercontent.com/12412734/197344877-e58d14b3-6b0a-45e9-a3d9-a0f0ebc746e4.png)

**Comment by magtimmermans** [comment]
Dankjewel. Ik heb standaard capabilities van homey gebruikt en die maakt er wh van. Ik zal dit in de volgende versie aanpassen.
