### ISSUE TITLE
EHOSTUNREACH, readings fail 

### ISSUE THREAD

**Issue by fmvdb** [magtimmermans/smartgateways#8]
Please read https://community.homey.app/t/smart-gateways-smart-meter-gateway-app-topic/73411 for more information

Homey quite often reports “Apparaat Onbeschikbaar request to http://192.168.1.87:82/smartmeter/api/read? failed, reason: connect EHOSTUNREACH 192.168.1.87:82”
At the moment when this error is present, I am able to connect to the device via its webinterface (by browsing manually to above url).

I investigated a bit further and concluded that at this moment the Homey app only does the first reading correct and the next readings give above connections issues (see above). This conclusion is based on:

If I change the polling interval in the app the first reading goes fine again, the second one after the given time interval gives again connection issues (I can check it with the stopwatch). During this time the webinterface keeps working.
If I restart the app, the first reading is fine again, the rest is exactly the same as by 1.
So my conclusion is that the app itself only does the first reading correct with the current version. I only don’t understand why

**Comment by magtimmermans** [comment]
Did you check the log? Could you send it to me?
It looks for me an unstable wifi network between homey and this Smartgateways device.

**Comment by fmvdb** [comment]
Do you mean this log available in the app?

https://tweakers.net/i/IORmtpjhCg3KoXIjOssLz5zCh7w=/full-fit-in/4920x3264/filters:max_bytes(3145728):no_upscale():strip_icc():fill(white):strip_exif()/f/image/MUoGIaL2fo3gzcPqRLdqrUmF.jpg?f=user_large

**Comment by magtimmermans** [comment]
Yes

**Comment by magtimmermans** [comment]
Could you try updating once a minute

**Comment by fmvdb** [comment]
Just changed it for both to 60s
I also notice that the 1st values shown in the app directly after changing the polling interval are not actual ones, seem to be the latest successfully read values and Homey shows these are from 1 day ago.
After 60s the communication error shows again.

**Comment by magtimmermans** [comment]
Homey will cash the values if it cant read new once. 
Do you have the latest firmware of Smartgateways p1 meter?
The only thing I can think of is that one of the devices has bad wifi connection.

**Comment by fmvdb** [comment]
Ok thnx for the info.

I’m using the following device and (latest) firmware:
Device: [Slimme meter wifi gateway - SmartGateways.nl 1](https://smartgateways.nl/product/slimme-meter-wifi-gateway/)
Device firmware version: 2022120601

**Comment by fmvdb** [comment]
I don’t suspect wifi issues given the fact that it has been working without issues since the summer, so for approximately 6 months
Additionally I can reach the smart meter with its webinterface

**Comment by magtimmermans** [comment]
That's wierd indeed. Is there a recent change? Homey update? Wifi update? Change  in Wi-Fi radio channels?

**Comment by fmvdb** [comment]
No changes in network on my side.
Don’t know about a Homey update, need to find out if and when that happened. 
Also I did not do a firmware update of the smart meter, I only started updating the firmware to trouble shoot; so after the issues where there

**Comment by fmvdb** [comment]
Somehow it is working stable again for more than 10 days now. Didn’t change anything by myself, so still unclear what happened. I’ll keep monitoring but it looks like the issue can be closed.

**Comment by magtimmermans** [comment]
Wierd, could you have influence from neighborhood wifi's that maybe disturbed your signal a bit?

**Comment by fmvdb** [comment]
No, that can hardly be the case. I have a well isolated house with little Wifi influence from outside. And on top I have 1 or 2 Wifi accesspoints (unify) on each floor so Wifi coverage is very good  ;-)

Only thing I noticed is: 
I have two Wifi smartgateways devices, one for the electricity+gas and one other for the watermeter.
In roughly the same period (but not exactly the same) I tried several times to update the firmware of the “watermeter-smartgateways”. This firmware process did not go fluent, it took several days until it was completed…
I can hardly imagine it, since it are seperate devices. But maybe it interfered with the “electricity+gas-smartgateways”. Both had issues getting the data from them.

**Comment by magtimmermans** [comment]
I have a similar setup. 4 unify acces points.  Also using the p1 meter and water meter. That works well. I had a year ago problems (connecting/disconnecting/not reachable) with esp devices and I changed some settings and now I t is working flawless. For example Esp devices don't like auto channel and some other things. Anyway for now it is fixed and I will close the case.

**Comment by fmvdb** [comment]
Last summer I had a lot of Wifi connection issues, but those were caused by a specific firmware version of the smartgateways. Since then it all worked without any issue.

closing is fine, I’ll keep monitoring it and let you know if it occurs again.
