### ISSUE TITLE
Watermeter gateways - waterlekdetectie

### ISSUE THREAD

**Issue by rjoomen** [magtimmermans/smartgateways#9]
Beste Marcel,

Zou je voor de watermeter de lekdetectiefunctionaliteit kunnen toevoegen? In de REST API gaat het om `"leak_detect":boolean`, die gekoppeld kan worden aan de Homey capability `alarm_water`.

(Ik kwam hier eigenlijk om het zelf op te lossen en je een pull request te sturen, maar de broncode ontbreekt, helaas).

Groeten,
Roelof

**Comment by magtimmermans** [comment]
Toegevoegd.

https://homey.app/a/com.cyclone-software.smartgateways/test/

**Comment by rjoomen** [comment]
Dat is snel, hartelijk dank!

Het device in Homey kreeg trouwens pas na verwijderen en opnieuw toevoegen de nieuwe capability, ik vermoed dat je geen addCapability() toegevoegd hebt in de code om bestaande devices op te waarderen, zie hier: https://apps.developer.homey.app/guides/how-to-breaking-changes#adding-capabilities
